Code style improvements
worldline/ProSA pull request #12
Opened 2024-08-29 22:26 UTC by oschijns

Removed the `Default` trait requirement for the `Adaptor` trait such that adaptors can be instantiated with embedded data.
Renamed multiple enum variants from capital case to pascal casee to follow Rust coding convention.
Introduced a `Id` alias type for TVF fields' identifiers.

2024-08-30 07:19 UTC, reneca requested changes
You need to update ProSA version in Cargo.toml to 0.2.0 since you're making breaking changes.

Also please adapt processors **Inj** and **Stub** to use a _new_ function instead of a _Default_ + _init_
ex.
```
// Initiate an adaptor for the inj processor
let mut adaptor = A::default();
adaptor.init(self)?;
```
become
```
// Initiate an adaptor for the inj processor
let mut adaptor = A::new(self)?;
```

And remove the Default trait in the where clause

2024-08-30 07:19 UTC, reneca commented on prosa/src/core/main.rs
>              .map_err(|e| BusError::InternalMainQueueError("DELPROC".into(), proc_id, e.to_string()))
Rename InternalMainQueueError return with the modified name instead of uppercases

2024-08-30 07:19 UTC, reneca commented on prosa_macros/src/tvf.rs
> +type Id = usize;
For me, there is no gain to put a specific type for TVF key type.
It just add the need to import this specific type if you use TVF.

We'll add nothing to it specifically.

2024-09-04 13:12 UTC, oschijns commented on prosa_macros/src/tvf.rs
> +type Id = usize;
Change dropped because it would make more sense to bind the `Id` type to the `TVF` trait.

2024-10-01 10:58 UTC, reneca approved these changes

2024-10-02 09:51 UTC, Timmy80 reviewed
Review OK

2024-10-02 09:52 UTC, reneca approved these changes

2024-10-02 09:52 UTC, Timmy80 approved these changes

2024-10-02 09:52 UTC, merged